Fiap.Exemplo03.MVC/Fiap.Exemplo03.MVC/Models/Animal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo03.MVC.Models
{
    public class Animal
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Nome { get; set; }
        [Display(Name = "Data de Nascimento")]
        public DateTime DataNascimento { get; set; }
        public string Especie { get; set; }
    }
}

Fiap.Exemplo03.MVC/Fiap.Exemplo03.MVC/Controllers/AnimalController.cs
using Fiap.Exemplo03.MVC.Models;
using Fiap.Exemplo03.MVC.Persistencia;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo03.MVC.Controllers
{
    public class AnimalController : Controller
    {
        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Animal animal)
        {
            var context = new ZooContext();
            context.Animais.Add(animal);
            context.SaveChanges();
            return View();
        }

        [HttpGet]
        public ActionResult Listar()
        {
            var context = new ZooContext();
            List<Animal> animais = context.Animais.ToList();
            return View(animais);
        }

    }
}

Fiap.Exemplo03.MVC/Fiap.Exemplo03.MVC/Views/Animal/Cadastrar.cshtml
@model Fiap.Exemplo03.MVC.Models.Animal

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(i => i.Nome)
        @Html.TextBoxFor(i => i.Nome, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(b => b.DataNascimento)
        @Html.TextBoxFor(b => b.DataNascimento, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(b => b.Especie)
        @Html.TextAreaFor(b => b.Especie, new { @class = "form-control" })
    </div>

    <input type="submit" value="Salvar" class="btn btn-primary" />
}

Fiap.Exemplo03.MVC/Fiap.Exemplo03.MVC/Views/Animal/Listar.cshtml
@model List<Fiap.Exemplo03.MVC.Models.Animal>

@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

<table class="table">
    <tr>
        <th>Nome</th>
        <th>Data de Nascimento</th>
        <th>Espécie</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nome</td>
            <td>@item.DataNascimento.ToShortDateString()</td>
            <td>@item.Especie</td>
        </tr>
    }
</table>

Fiap.Exemplo03.MVC/Fiap.Exemplo03.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cadastrar Animal", "Cadastrar", "Animal", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Listar Animal", "Listar", "Animal", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>