Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Models/Boteco.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo02.MVC.Models
{
    public class Boteco
    {
        public int Id { get; set; }
        public string Nome{ get; set; }
        public string Endereco { get; set; }
        public bool MusicaAoVivo { get; set; }
        public decimal Consumacao { get; set; }
        public DateTime DataInauguracao { get; set; }
    }
}

Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Models/Cerveja.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo02.MVC.Models
{
    public class Cerveja
    {
        public string Nome { get; set; }
        public string Marca { get; set; }
        public decimal Preco { get; set; }
        public bool SemAlcool { get; set; }
        public string Tipo { get; set; }
        public DateTime Validade { get; set; }
    }
}

Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Controllers/BotecoController.cs
using Fiap.Exemplo02.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo02.MVC.Controllers
{
    public class BotecoController : Controller
    {
        //Simular o banco de dados
        private static List<Boteco> _banco = new List<Boteco>();

        //Abre a tela com o formulário
        [HttpGet]
        public ActionResult Cadastro()
        {
            return View();
        }

        [HttpPost]
        //Cadastrar de verdade
        public ActionResult Cadastro(Boteco boteco)
        {
            //Cadastrar no banco
            _banco.Add(boteco);
            //Mensagem de sucesso
            TempData["msg"] = "Cadastrado com sucesso!";
            return View();
        }

        [HttpGet]
        public ActionResult Listar()
        {
            //Passar os botecos cadastrados p/ view
            return View(_banco);
        }
    }
}

Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Controllers/CervejaController.cs
using Fiap.Exemplo02.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo02.MVC.Controllers
{
    public class CervejaController : Controller
    {
        private static List<Cerveja> _banco = new List<Cerveja>();
        private static List<String> _tipos = new List<String>();

        [HttpGet]
        public ActionResult Cadastrar()
        {
            _tipos.Add("Large");
            _tipos.Add("Pilsen");
            _tipos.Add("Red Ale");
            _tipos.Add("Weiss");
            //Passar para a tela
            ViewBag.tipos = new SelectList(_tipos);
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Cerveja cerveja)
        {
            TempData["msg"] = "Cadastrado!";
            _banco.Add(cerveja);
            ViewBag.tipos = new SelectList(_tipos);
            return View();
        }

        [HttpGet]
        public ActionResult Listar()
        {
            return View(_banco);
        }
    }
}

Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Views/Boteco/Cadastro.cshtml
@model Fiap.Exemplo02.MVC.Models.Boteco

@{
    ViewBag.Title = "Cadastro";
}

<h2>Cadastro</h2>

@Ajuda.Message(@TempData["msg"] as string)

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(i => i.Nome)
        @Html.TextBoxFor(i => i.Nome, new { @class = "form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(b => b.DataInauguracao)
        @Html.TextBoxFor(b => b.DataInauguracao, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(b => b.Endereco)
        @Html.TextAreaFor(b => b.Endereco, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(b => b.Consumacao)
        @Html.TextBoxFor(b => b.Consumacao, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.CheckBoxFor(b => b.MusicaAoVivo)
        @Html.LabelFor(b => b.MusicaAoVivo)
    </div>
    <input type="submit" value="Salvar" class="btn btn-primary" />
}


@section Scripts{
    <p>Código javascript...</p>    
}

Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Views/Boteco/Listar.cshtml
@model List<Fiap.Exemplo02.MVC.Models.Boteco>

@{
    ViewBag.Title = "Listar";
}

<h2>Lista de Boteco</h2>

<table class="table">
    <tr>
        <th>Nome</th>
        <th>Data Inauguração</th>
        <th>Endereço</th>
        <th>Musica ao Vivo</th>
        <th>Consumação</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nome</td>
            <td>@item.DataInauguracao.ToShortDateString()</td>
            <td>@item.Endereco</td>
            <td>@item.MusicaAoVivo</td>
            <td>@item.Consumacao</td>
        </tr>
    }
</table>

Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Views/Cerveja/Cadastrar.cshtml
@model Fiap.Exemplo02.MVC.Models.Cerveja
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(c => c.Nome)
        @Html.TextBoxFor(c => c.Nome, new { @class = "form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Marca)
        @Html.TextBoxFor(c => c.Marca, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Preco)
        @Html.TextBoxFor(c => c.Preco, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Validade)
        @Html.TextBoxFor(c => c.Validade, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Tipo)
        @Html.DropDownListFor(c => c.Tipo,
               ViewBag.tipos as SelectList ,new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.CheckBoxFor(c => c.SemAlcool)
        @Html.LabelFor(c => c.SemAlcool)
    </div>
    <input type="submit" value="Salvar" class="btn btn-primary" />
}

Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Views/Cerveja/Listar.cshtml
@model List<Fiap.Exemplo02.MVC.Models.Cerveja>
@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

<table class="table">
    <tr>
        <th>Nome</th>
        <th>Tipo</th>
        <th>Validade</th>
        <th>Marca</th>
        <th>Sem Alcool</th>
        <th>Preço</th>
    </tr>
    @foreach (var item in Model)
    {
        @Html.Partial("_linhaTabela", item)
    }
</table>

Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Views/Cerveja/_linhaTabela.cshtml
@model Fiap.Exemplo02.MVC.Models.Cerveja

<tr>
    <td>@Model.Nome</td>
    <td>@Model.Tipo </ td >
    <td>@Model.Validade </ td >
    <td>@Model.Marca </ td >
    <td>@Model.SemAlcool </ td >
    <td>@Model.Preco </ td >
</tr>

Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Fiap.Exemplo02.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FIAP Bar", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Boteco <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastro", "Cadastro", "Boteco")</li>
                            <li>@Html.ActionLink("Lista", "Listar", "Boteco")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cerveja <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastro", "Cadastrar", "Cerveja")</li>
                            <li>@Html.ActionLink("Lista", "Listar", "Cerveja")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @RenderSection("Scripts", false)
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>